/*

Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 
terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.

*/

function sumEvenFibonacci(limit) {
    let sumEven;
    let sequence = [1,2];

    for(i = 0; sequence[sequence.length - 1] < limit-1; i++){
        sequence.push(sequence[i] + sequence[i+1])
    }

    sumEven = sequence.filter((x) => x%2 === 0)
                      .reduce((acc, cur) => acc + cur);

    return sumEven;
}

const limit = 4000000;
console.time('Time');
console.log('Answer: ' + sumEvenFibonacci(limit));
console.timeEnd('Time');
